### PR TITLE
Following comments from WP Theme Review team

### PR DESCRIPTION
**Pull request by nuritsha**

### CODE REVIEW

**Comment by alriksson** [comment]
Seems like the readme and hooks is not up to date since of your changes of the naming conventions of the hooks?

**Comment by alriksson** [comment]
What will be used now seems like it's forked version and the main version have different readme? can we get it into wordpress repo for an easy update? Can I update a theme the same way as a plugin with extract the zip file within /wp-content/theme ?

**Comment by nuritsha** [comment]
Hi @alriksson,

This is exactly what we are working on right now. 
Once the theme is approved, it will be available in the WP repo and will be updated the same way any other theme does.

**Comment by alriksson** [comment]
That sounds great! Until then how do I update the theme? And should I change any hook if I update the theme?
Is it still this updated as latest version now?: https://github.com/elementor/elementor-hello-theme and which hook?
```
add_filter( 'hello_elementor_add_woocommerce_support', '__return_false' );
add_filter( 'elementor_hello_theme_add_woocommerce_support', '__return_false' );

```

**Comment by nuritsha** [comment]
To update, take the latest version from git ( ver 2.0.0 ).
Better use the new name - `hello_elementor_add_woocommerce_support`.

**Comment by alriksson** [comment]
And the latest version is a clone and download this: https://github.com/elementor/elementor-hello-theme

Can I extract it in sftp in `/wp-content/themes` to update it in an easy and smooth way?

Ok thanks will do!

Once it's in the WP repo would It require to reinstall the theme from wp repo or will it automatically be connected to each other?

**Comment by alriksson** [comment]
> Can I extract it in sftp in /wp-content/themes to update it in an easy and smooth way?

Worked like a charm, but let's answer the other comments regarding if I would need to switch to the wp repo theme later on once available. And what the ETA is for that.

**Comment by nuritsha** [comment]
Glad to hear :)
Unfortunately the schedule is not up to us. We are waiting for the Theme review to complete and only then will be able to answer your questions regarding the repo etc'.

**Comment by alriksson** [comment]
Ok, thanks for the answers :)

**Pull request closed without merging**
